trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    - features/*
  paths:
    exclude: [ 'README.md' ]

jobs:
- job: BuildWindows

  pool:
    vmImage: 'windows-latest'

  variables:
    BUILD_PATH: '$(Build.BinariesDirectory)'

  steps :
    - script: |
        set -e
        git clone --branch v2.0.2 --depth=1 https://github.com/bitcoin-sv/block-headers-client.git $(BUILD_PATH)
      displayName: 'clone'

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        cd $(BUILD_PATH)
        .\gradlew.bat assemble
      displayName: 'assemble'

    - script: |
        cd $(BUILD_PATH)
        copy app\build\distributions\app-boot-2.0.2.zip app\build\distributions\headersv-boot-2.0.2.zip
      displayName: 'rename build file'

    - task: PublishBuildArtifacts@1
      displayName: 'upload artifact'
      inputs:
        artifactName: 'WindowsHeaderSV'
        pathtoPublish: '$(BUILD_PATH)\app\build\distributions\headersv-boot-2.0.2.zip'
